name: Linting

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  linting_python_django:
    name: Linting Python and Django
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Check Python rules via pycodestyle
        run: pycodestyle *.py accounts/*.py datenmanagement/*.py datenmanagement/*/*.py datenwerft/*.py
      - name: Check Django rules via djLint
        run: djlint templates/*.html accounts/templates/accounts/log*.html datenmanagement/templates/datenmanagement/*.html
  linting_js_css:
    name: Linting JavaScript and CSS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: Install Node.js dependencies
        run: npm install
      - name: Check CSS rules via Stylelint
        run: npx stylelint "accounts/**/*.css" "datenmanagement/**/*.css"
      - name: Check JavaScript rules via ESLint
        run: npx eslint "datenmanagement/static/datenmanagement/js/*.js" "datenmanagement/templates/datenmanagement/list.html"
