name: Linting

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

  workflow_dispatch:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: Install Node.js dependencies
        run: npm install
      - name: Check CSS rules via Stylelint
        run: stylelint "accounts/**/*.css" "datenmanagement/**/*.css"
