name: generate plantuml
on: push
jobs:
  generate_plantuml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate PlantUML Diagrams
        uses: rotaract/plantuml-action@v1
        with:
          format: svg
          pattern: "**.puml"

      - name: Upload Diagrams
        uses: actions/upload-artifact@v3
        with:
          name: diagrams
          path: "**.svg"
