name: generate plantuml
on:
  push:
    paths: 
      - "**.puml"
    branches: 
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
jobs:
  generate_plantuml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate PlantUML Diagrams
        uses: rotaract/plantuml-action@v1
        with:
          format: svg
          pattern: "**.puml"

      - name: Upload Diagrams
        uses: actions/upload-artifact@v4
        with:
          name: diagrams
          path: "**.svg"
