name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

env:
  POSTGRES_USER: postgres
  POSTGRES_PASS: postgres
  POSTGRES_DBNAME: datenwerft

jobs:
  tests:
    name: Tests on all apps
    runs-on: ubuntu-latest
    services:
      openldap:
        image: bitnami/openldap:latest
        env:
          LDAP_ROOT: dc=example,dc=org
          LDAP_ADMIN_USERNAME: admin
          LDAP_ADMIN_PASSWORD: password
          LDAP_USERS: user01,user02
          LDAP_PASSWORDS: password1,password2
        ports:
          - 1389:1389
      postgres:
        image: kartoza/postgis
        env:
          POSTGRES_USER: $POSTGRES_USER
          POSTGRES_PASS: $POSTGRES_PASS
          POSTGRES_DBNAME: $POSTGRES_DBNAME
          PASSWORD_AUTHENTICATION: md5
          ALLOW_IP_RANGE: 0.0.0.0/0
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install prerequisites
        run: sudo apt-get install postgresql-client
      - name: Create database schema
        env:
          PGPASSWORD: ${{ env.POSTGRES_PASS }}
        run: psql -h localhost -U $POSTGRES_USER -d $POSTGRES_DBNAME -f datenmanagement/sql/schema.sql
