name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

env:
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: datenwerft

jobs:
  tests:
    name: Tests on all apps
    runs-on: ubuntu-latest
    services:
      openldap:
        image: bitnami/openldap:latest
        env:
          LDAP_ROOT: dc=example,dc=org
          LDAP_ADMIN_USERNAME: admin
          LDAP_ADMIN_PASSWORD: password
          LDAP_USERS: user01,user02
          LDAP_PASSWORDS: password1,password2
        ports:
          - 1389:1389
      postgres:
        image: postgis/postgis
        env:
          POSTGRES_PASSWORD: $POSTGRES_PASSWORD
          POSTGRES_DB: $POSTGRES_DB
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install prerequisites
        run: sudo apt-get install postgresql-client
      - name: Create database schema
        env:
          PGPASSWORD: ${{ env.POSTGRES_PASSWORD }}
        run: psql -d postgresql://postgres@localhost/datenwerft -f datenmanagement/sql/schema.sql
