name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  tests:
    name: Tests on all apps
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgis/postgis
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: datenwerft
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install prerequisites for Python dependencies
        run: sudo apt-get install gdal-bin libgdal-dev libldap2-dev libpq-dev libsasl2-dev postgresql-client
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Create further settings file based on corresponding template
        run: cp datenwerft/secrets.template datenwerft/secrets.py
      - name: Create database schema for app datenmanagement
        run: psql -h postgres -U postgres -d datenwerft -f datenmanagement/sql/schema.sql
      - name: Run migrations
        run: python manage.py migrate
      - name: Run tests on app Accounts
        run: python manage.py test accounts
